# Generated by Django 3.0.7 on 2020-07-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200701_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=' '),
        ),
    ]
