# Generated by Django 3.0.7 on 2020-07-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200701_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=' ')),
                ('genre', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=' ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User')),
            ],
        ),
    ]
